---
kind: pipeline
name: Conf_synth
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: push_to_ecr
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: dsa/conf_synth_refresh
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    region: eu-west-2
    create_repository: false
    tags:
    - latest

trigger:
  branch:
  - dev
  event:
  - push