kind: pipeline
name: conf_synth

steps:
- name: publish  
  image: plugins/ecr
  settings:
    access_key: 
      from_secret: AWS_ACCESS_KEY
    secret_key: 
      from_secret: AWS_SECRET_KEY
    repo: dsa/conf_synth_refresh
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com




# steps:
# - name: push_to_quay
#   image: plugins/docker
#   settings:
#     username: aminah100216
#     password: Gu+MvWH3Dmj1kEWGOAqY25iIhWokFGwD4xFqtklJ/bAmgxjNZ5Pql/eeLZ7ooG6N
#     repo: quay.io/ukhomeofficedigital/conf-synth-refresh
#     registry: quay.io
#     tags: latest

    

# steps:
# - name: conf_synth_image
#   image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
#   pull: if-not-exists
#   commands:
#   - ./push_to_repo.sh
# trigger:
#   branch:
#   - dev
#   event:
#   - push

