---
kind: pipeline
name: Conf_synth_data
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: push_conf_synth 
  image: plugins/ecr
  settings:
    access_key: 
      from_secret: AWS_ACCESS_KEY
    secret_key: 
      from_secret: AWS_SECRET_KEY
    repo: dsa/conf_synth_refresh
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    region: eu-west-2
    create_repository: false
    # build_args:
    # - APP_BUILD=${DRONE_COMMIT_SHA}
    # - DOCKER_HOST=tcp://172.17.0.1:2375
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}

trigger:
  branch:
  - dev
  event:
  - push


# steps:
# - name: push_to_quay
#   image: plugins/docker
#   settings:
#     username: aminah100216
#     password: Gu+MvWH3Dmj1kEWGOAqY25iIhWokFGwD4xFqtklJ/bAmgxjNZ5Pql/eeLZ7ooG6N
#     repo: quay.io/ukhomeofficedigital/conf-synth-refresh
#     registry: quay.io
#     tags: latest

    

# steps:
# - name: conf_synth_image
#   image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
#   pull: if-not-exists
#   commands:
#   - ./push_to_repo.sh
# trigger:
#   branch:
#   - dev
#   event:
#   - push



# - name: build_push_to_ecr
#   image: plugins/ecr
#   # image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/ecr
#   settings:
#     access_key:
#       from_secret: AWS_ACCESS_KEY_ID
#     secret_key:
#       from_secret: AWS_SECRET_ACCESS_KEY
#     repo: dsa/jira_synth_refresh
#     registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
#     region: eu-west-2
#     create_repository: false
#     build_args:
#     - APP_BUILD=${DRONE_COMMIT_SHA}
#     - DOCKER_HOST=tcp://172.17.0.1:2375
#     tags:
#     - latest
#     - ${DRONE_COMMIT_SHA}
